font_family				FiraCode
font_size				11
disable_ligatures		never

detect_urls				yes
url_color 				#00ffff
url_style 				straight
show_hyperlink_targets	yes
copy_on_select			no

enable_audio_bell		no

window_margin_width			0
single_window_margin_width	-1
tab_bar_edge				bottom
tab_bar_style				powerline
tab_powerline_style			slanted

foreground			#f2f4f3
background			#0f050d
background_opacity		0.9

color0				#000000
color8				#494949
color1				#e3256b
color9				#e9558b
color2				#6be326
color10				#96eb64
color3				#e3d26d
color11				#ede974
color4				#6d7fe3
color12				#a1aded
color5				#e36ddd
color13				#eda1e9
color6				#6ddde3
color14				#a1e9ed
color7				#dbdbdb
color15				#ffffff
