backend = "glx"
shadow-radius = 14;
shadow-offset-x = -15;
shadow-offset-y = -15;
shadow-opacity = 0.75;

corner-radius = 8;

blur-method = "dual_kawase";
blur-strength = 7
blur-rule = [
	"class_g = 'kitty'",
	"class_g = 'Polybar'",
	"class_g = 'code-oss'"
];

fading = true;
fade-delta = 4;
fade-in-step = 0.03;
fade-out-step = 0.03;
