backend = "glx"
shadow-radius = 14;
shadow-offset-x = -15;
shadow-offset-y = -15;
shadow-opacity = 0.75;

corner-radius = 8;

experimental-backends = true;

blur: {
	method = "dual_kawase";
	strength = 4;
	background = false;
	background-frame = false;
	background-fixed = false;

	blur-exclude : [
		"peek"
	];
}

fading = true;
fade-delta = 4;
fade-in-step = 0.03;
fade-out-step = 0.03;

vsync = true;
