#! /bin/sh

killall sxhkd; sxhkd &
killall dunst; dunst &
nitrogen --restore &
killall picom; picom &
killall polybar; polybar &
killall unclutter; unclutter --timeout 1 --jitter 32 --start-hidden &
alsactl restore -f ~/.alsactlrestore &
kilall rclone; rclone mount --daemon gdrive: /home/rudyon/gdrive &

setxkbmap -option caps:backspace
xmodmap -e "clear Lock"

bspc monitor -d 1 2 3

bspc config border_width 1 
bspc config window_gap 12 

bspc config split_ratio 0.5
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config pointer_follows_focus false
bspc config focus_follows_pointer false

bspc config focused_border_color "#e3256b"
bspc config normal_border_color "#073642"
bspc config active_border_color "#073642"
