#! /bin/sh

killall sxhkd; sxhkd &
killall dunst; dunst &
nitrogen --restore &
killall picom; picom &
killall polybar; polybar default; polybar extra &
killall unclutter; unclutter --timeout 0 --jitter 32 --start-hidden &
alsactl restore -f /home/rudyon/.alsarestore &

setxkbmap -option "caps:backspace"
xmodmap -e "clear Lock"

bspc monitor -d 1 2 3 4

bspc config border_width 1 
bspc config window_gap 12 

bspc config top_padding 36

bspc config split_ratio 0.5
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config pointer_follows_focus false
bspc config focus_follows_pointer false

bspc config focused_border_color "#e3256b"
bspc config normal_border_color "#073642"
bspc config active_border_color "#073642"

bspc rule -a feh state=pseudo_tiled
